version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  discord-bot:
    image: ghcr.io/kings-world/fabric-microservice:latest
    container_name: discord-bot
    build: .
    env_file: .docker.env
    depends_on:
      - redis
